[package]
name = "captura-hub"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
regex.workspace = true
serde.workspace = true
serde_yaml.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true
captura-common = { path = "../common" }
reqwest.workspace = true
chrono.workspace = true
async-trait.workspace = true
captura-extract = { path = "../extract" }
captura-net = { path = "../net" }
scraper.workspace = true
once_cell.workspace = true
inventory.workspace = true
captura-hub-macros = { path = "../hub-macros" }
captura-fetcher = { path = "../fetcher" }
