[package]
name = "captura-webui"
version.workspace = true
edition.workspace = true

[lib]
name = "captura_webui"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
askama.workspace = true
mime.workspace = true
rust-embed.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio.workspace = true
tower-http.workspace = true
reqwest.workspace = true
url.workspace = true
once_cell.workspace = true
urlencoding.workspace = true
base64.workspace = true
rand_core.workspace = true
captura-net = { path = "../net" }
captura-types = { path = "../types" }
