[package]
name = "captura-api"
version.workspace = true
edition.workspace = true

[lib]
name = "captura_api"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
axum-extra.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sea-orm.workspace = true
chrono.workspace = true
captura-common = { path = "../common" }
captura-storage = { path = "../storage" }
captura-migration = { path = "../migration" }
captura-hub = { path = "../hub" }
captura-fetcher = { path = "../fetcher" }
captura-crawler = { path = "../crawler" }
captura-scheduler = { path = "../scheduler" }
captura-pipeline = { path = "../pipeline" }
captura-service = { path = "../service" }
captura-types = { path = "../types" }
captura-net = { path = "../net" }
sha2.workspace = true
argon2.workspace = true
rand_core.workspace = true
headers.workspace = true
quick-xml.workspace = true
url.workspace = true
md-5.workspace = true
base64.workspace = true
reqwest.workspace = true
scraper.workspace = true
once_cell.workspace = true
regex.workspace = true
urlencoding.workspace = true
hex.workspace = true
tower-http.workspace = true
hmac.workspace = true
openidconnect.workspace = true
captura-webui = { path = "../webui" }

[dev-dependencies]
http-body-util.workspace = true
futures.workspace = true
tower.workspace = true
captura-testkit = { path = "../testkit" }
