[package]
name = "captura-service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
sea-orm.workspace = true
captura-common = { path = "../common" }
captura-storage = { path = "../storage" }
captura-pipeline = { path = "../pipeline" }
tracing.workspace = true
reqwest.workspace = true
ammonia.workspace = true
hmac.workspace = true
sha2.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
